config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-dark">
  <div class="container">
    <span class="text-white">Copyright <%= link_to "Navis", "http://navis.com", class: "text-white" %></span>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
<% flash.each do |name, msg| %>
  <div class="alert <%= name=="notice"? "alert-success":"alert-danger" %> alert-dismissible fade show role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= msg %>
  </<div>
<%end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
       <ul class="navbar-nav mr-auto">
         <li class="nav-item ">
           <%= link_to "Bloggers", users_path, class: "nav-link"%>
         </li>
         <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             Articles
           </a>
           <div class="dropdown-menu" aria-labelledby="navbarDropdown">
             <% if logged_in? %>
              <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
             <% end %>
             <%= link_to "View articles", articles_path, class: "dropdown-item" %>
             <div class="dropdown-divider"></div>
             <a class="dropdown-item" href="#">Something else here</a>
           </div>
         </li>

         <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             Categories
           </a>
           <div class="dropdown-menu" aria-labelledby="navbarDropdown">
             <% if logged_in? && current_user.admin? %>
              <%= link_to "Create new Category", new_category_path, class: "dropdown-item" %>
             <% end %>
             <%= link_to "View Categories", categories_path, class: "dropdown-item" %>
           </div>
         </li>

         <% if logged_in? %>
           <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <%="(Admin)" if current_user.admin?%> Profile [<%= current_user.username %>]
             </a>
             <div class="dropdown-menu" aria-labelledby="navbarDropdown">
               <%= link_to "View Your Profile", user_path(current_user), class: "dropdown-item" %>
               <%= link_to "Edit Your Profile", edit_user_path(current_user), class: "dropdown-item" %>
               <%= link_to "Delete Profile", user_path(current_user), class: "dropdown-item text-danger btn btn-outline-danger",
                                          method: :delete, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
             </div>
           </li>

           <li class = "nav-item">
             <%= link_to "Log Out", logout_path, class: "btn btn-outline-info", data: {turbo_method: :delete} %>
           </li>

         <% else %>
           <li class = "nav-item">
             <%= link_to 'Log In', login_path, class: "nav-link"%>
           </li>

           <li class = "nav-item">
             <%= link_to 'Sign Up', signup_path, class: "nav-link"%>
           </li>

         <% end %>

      </ul>

       <form class="form-inline my-2 my-lg-0">
         <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
         <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
       </form>

      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

    <!-- need the following two lines for the dropdowns to work properly in Rails 7 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>